source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'APValidators_Example' do
  pod 'APValidators', :path => '../'

  	target 'APValidators_Tests' do
		inherit! :search_paths
		pod 'Expecta'
		pod 'OCMock'
	end
end
